#!/usr/bin/env bash
# Install nginx and set up the web server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo update-rc.d nginx defaults
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart